remote_theme: pages-themes/dinky@v0.2.0
title: [What would happen if the real life would work in books?]
description: [I choose as my mission to search up for you and finally understand would famous books work if the medicine and physics would have worked there in traditional way.]

